#!/bin/sh

set -eu

. helpers.sh

source_hook pre clean-build-directory

test -f Makefile && make distclean
rm -rf autom4te.cache/ build/ include/ modules/ config.h config.h.in config.nice configure configure.ac run-tests.php

source_hook post clean-build-directory
