#!/bin/sh

set -eu

. helpers.sh

clean-build-directory

source_hook pre configure

phpize

CONFIGURE_SCRIPT="./configure"
if [ -x "build-hooks/configure" ]; then
    CONFIGURE_SCRIPT="build-hooks/configure"
fi

"${CONFIGURE_SCRIPT}" CFLAGS="${CFLAGS:-} ${EXTENSION_CFLAGS:-}" CXXFLAGS="${CXXFLAGS:-} ${EXTENSION_CFLAGS:-}"

source_hook post configure

build-extension
